# Generated by Django 4.2.1 on 2023-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='CVV',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='card',
            name='ExpiryDate',
            field=models.CharField(default='01/01', max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='OwnerName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='Type',
            field=models.CharField(choices=[('CREDITO', 'Tarjeta de credito'), ('DEBITO', 'Tarjeta de debito')], default='', max_length=100),
        ),
    ]
