# Generated by Django 4.2.1 on 2023-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_cvv_card_expirydate_card_ownername_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(max_length=5000),
        ),
    ]
