# Generated by Django 4.2.1 on 2023-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_user_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
