# Generated by Django 4.2.1 on 2023-07-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_invoice_client_remove_invoice_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Seller',
        ),
    ]
